<?XML VERSION="1.0"?>


<!--
	Bayesian network in BIF (BayesNet Interchange Format)
	Produced by JavaBayes (http://www.cs.cmu.edu/~javabayes/
	Output created Fri Nov 14 13:13:03 GMT+00:00 1997
-->



<!-- DTD for the BIF format -->
<!DOCTYPE BIF [
	<!ELEMENT PROPERTY (#PCDATA)>
	<!ELEMENT TYPE (#PCDATA)>
	<!ELEMENT VALUE (#PCDATA)>
	<!ELEMENT NAME (#PCDATA)>
	<!ELEMENT NETWORK
		( NAME, ( PROPERTY | VARIABLE | PROBABILITY )* )>
	<!ELEMENT VARIABLE ( NAME, TYPE, ( VALUE |  PROPERTY )* ) >
	<!ELEMENT PROBABILITY
		( FOR | GIVEN | TABLE | ENTRY | DEFAULT | PROPERTY )* >
	<!ELEMENT TABLE (#PCDATA)>
	<!ELEMENT DEFAULT (TABLE)>
	<!ELEMENT ENTRY ( VALUE* , TABLE )>
]>


<BIF>
<NETWORK>
<NAME>Car-Starts</NAME>

<!-- Variables -->
<VARIABLE>
	<NAME>Alternator</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Ok</VALUE>
	<VALUE>Faulted</VALUE>
	<PROPERTY>position = (47, 42)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>FanBelt</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Ok</VALUE>
	<VALUE>Slipping</VALUE>
	<VALUE>Broken</VALUE>
	<PROPERTY>position = (154, 42)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>Leak</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Leak</VALUE>
	<VALUE>NoLeak</VALUE>
	<PROPERTY>position = (245, 43)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>Charge</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Good</VALUE>
	<VALUE>Low</VALUE>
	<PROPERTY>position = (137, 125)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>BatteryAge</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>New</VALUE>
	<VALUE>Old</VALUE>
	<PROPERTY>position = (384, 42)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>BatteryState</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Ok</VALUE>
	<VALUE>Weak</VALUE>
	<PROPERTY>position = (371, 122)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>BatteryPower</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Good</VALUE>
	<VALUE>Poor</VALUE>
	<PROPERTY>position = (248, 197)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>GasInTank</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Gas</VALUE>
	<VALUE>NoGas</VALUE>
	<PROPERTY>position = (404, 198)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>GasGauge</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Gas</VALUE>
	<VALUE>NoGas</VALUE>
	<PROPERTY>position = (326, 247)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>Lights</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Work</VALUE>
	<VALUE>NoLight</VALUE>
	<PROPERTY>position = (137, 203)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>Radio</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Works</VALUE>
	<VALUE>Dead</VALUE>
	<PROPERTY>position = (165, 252)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>Starter</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Ok</VALUE>
	<VALUE>Faulted</VALUE>
	<PROPERTY>position = (177, 317)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>Leak2</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>True</VALUE>
	<VALUE>False</VALUE>
	<PROPERTY>position = (331, 315)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>EngineCranks</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Cranks</VALUE>
	<VALUE>NoCrank</VALUE>
	<PROPERTY>position = (248, 363)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>FuelPump</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Ok</VALUE>
	<VALUE>Faulted</VALUE>
	<PROPERTY>position = (186, 446)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>Distributor</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Ok</VALUE>
	<VALUE>Faulted</VALUE>
	<PROPERTY>position = (201, 506)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>SparkPlugs</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Ok</VALUE>
	<VALUE>Bad</VALUE>
	<PROPERTY>position = (264, 547)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>Starts</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Yes</VALUE>
	<VALUE>No</VALUE>
	<PROPERTY>position = (307, 443)</PROPERTY>
</VARIABLE>


<!-- Probability distributions -->
<PROBABILITY>
	<FOR>Alternator</FOR>
	<TABLE>0.9995 5.0E-4 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>FanBelt</FOR>
	<TABLE>0.995 0.0020 0.0030 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>Leak</FOR>
	<TABLE>1.0E-4 0.9999 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>Charge</FOR>
	<GIVEN>Alternator</GIVEN>
	<GIVEN>FanBelt</GIVEN>
	<GIVEN>Leak</GIVEN>
	<TABLE>0.0 1.0 0.0 0.0 0.0 0.0 0.5 0.5 0.5 0.5 0.5 0.5 1.0 0.0 1.0 1.0 1.0 1.0 0.5 0.5 0.5 0.5 0.5 0.5 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>BatteryAge</FOR>
	<TABLE>0.7 0.3 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>BatteryState</FOR>
	<GIVEN>BatteryAge</GIVEN>
	<TABLE>0.99 0.8 0.01 0.2 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>BatteryPower</FOR>
	<GIVEN>Charge</GIVEN>
	<GIVEN>BatteryState</GIVEN>
	<TABLE>1.0 0.0 0.0 0.0 0.0 1.0 1.0 1.0 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>GasInTank</FOR>
	<TABLE>0.5 0.5 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>GasGauge</FOR>
	<GIVEN>BatteryPower</GIVEN>
	<GIVEN>GasInTank</GIVEN>
	<TABLE>1.0 0.0 0.2 0.0 0.0 1.0 0.8 1.0 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>Lights</FOR>
	<GIVEN>BatteryPower</GIVEN>
	<TABLE>0.9 0.0 0.1 1.0 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>Radio</FOR>
	<GIVEN>BatteryPower</GIVEN>
	<TABLE>0.9 0.1 0.1 0.9 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>Starter</FOR>
	<TABLE>0.99 0.01 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>Leak2</FOR>
	<TABLE>1.0E-4 0.9999 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>EngineCranks</FOR>
	<GIVEN>BatteryPower</GIVEN>
	<GIVEN>Starter</GIVEN>
	<GIVEN>Leak2</GIVEN>
	<TABLE>0.0 1.0 0.0 0.0 0.0 0.2 0.0 0.0 1.0 0.0 1.0 1.0 1.0 0.8 1.0 1.0 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>FuelPump</FOR>
	<TABLE>0.999 0.0010 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>Distributor</FOR>
	<TABLE>0.999 0.0010 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>SparkPlugs</FOR>
	<TABLE>0.9998 2.0E-4 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>Starts</FOR>
	<GIVEN>EngineCranks</GIVEN>
	<GIVEN>FuelPump</GIVEN>
	<GIVEN>Distributor</GIVEN>
	<GIVEN>SparkPlugs</GIVEN>
	<TABLE>1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 </TABLE>
</PROBABILITY>


</BIF>
